apiVersion: apps/v1
kind: Deployment
metadata:
  name: wodify-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wodify
  template:
    metadata:
      labels:
        app: wodify
    spec:
      containers:
        - name: wodify
          ############## aws의 ecr 주소를 사용#############
          image: 730335238091.dkr.ecr.ap-northeast-2.amazonaws.com/wodify-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  key: REDIS_HOST
                  name: wodify-app-secrets
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: DB_HOST
                  name: wodify-app-secrets
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: DB_USERNAME
                  name: wodify-app-secrets
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: wodify-app-secrets
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET
                  name: wodify-app-secrets
            - name: JWT_SECRET_RT
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET_RT
                  name: wodify-app-secrets
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: AWS_ACCESS_KEY
                  name: wodify-app-secrets
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: AWS_SECRET_KEY
                  name: wodify-app-secrets

            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  key: SMTP_USERNAME
                  name: wodify-app-secrets
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SMTP_PASSWORD
                  name: wodify-app-secrets

            - name: MQ_HOST
              valueFrom:
                secretKeyRef:
                  key: MQ_HOST
                  name: wodify-app-secrets
            - name: MQ_USERNAME
              valueFrom:
                secretKeyRef:
                  key: MQ_USERNAME
                  name: wodify-app-secrets
            - name: MQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MQ_PASSWORD
                  name: wodify-app-secrets
